version: '3.3'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    command: gunicorn -w 4 application.wsgi -b 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=application.settings.prod
    volumes:
      - .:/code
      - ./static_files:/static_files
      - ./media_files:/media_files
    ports:
      - 8000:8000
    depends_on:
      - db
  cron:
    image: stockresources2_python:latest
    environment:
      - DJANGO_SETTINGS_MODULE=application.settings.dev
    volumes:
      - .:/code
    entrypoint: sh /code/docker/dev/cron/entrypoint.sh
    depends_on:
      - python
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./static_files:/static_files
      - ./media_files:/media_files
    depends_on:
      - python
volumes:
  postgres_data:
  static_files:
  media_files:
